name: Docker Nginx Deploy to EC2 via Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-web:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-web:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Update demo.yaml with latest image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-web:latest|" demo.yaml

      - name: Copy demo.yaml to EC2 and apply
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no demo.yaml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/demo.yaml
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e
            echo "📦 Applying Kubernetes manifest..."
            kubectl apply -f /home/ubuntu/demo.yaml
            echo "✅ Deployment complete."
          EOF
