name: Auto-Deploy index.html to EC2 Apache

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Upload index.html to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/tmp/index.html

      - name: Deploy index.html on Apache
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Move the uploaded file to Apache web root
            sudo mv /tmp/index.html /var/www/html/index.html

            # Set correct permissions (optional but safe)
            sudo chown www-data:www-data /var/www/html/index.html
            sudo chmod 644 /var/www/html/index.html

            # Restart Apache to reflect changes (optional)
            sudo systemctl restart apache2

            echo "✅ index.html deployed successfully!"
          EOF
