name: Deploy Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Save EC2 Key
      run: |
        echo "${{ secrets.EC2_KEY_PEM }}" > ec2-key.pem
        chmod 600 ec2-key.pem  # Correct file permissions

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 15.206.222.96 >> ~/.ssh/known_hosts

    - name: Fix Apache Directory Permissions
      run: |
        ssh -i ec2-key.pem ubuntu@15.206.222.96 "sudo chown -R ubuntu:ubuntu /var/www/html/"

    - name: Copy index.html to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 15.206.222.96
        username: ubuntu
        key: ec2-key.pem
        source: "index.html"
        target: "/var/www/html/"

    - name: Restart Apache
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 15.206.222.96
        username: ubuntu
        key: ec2-key.pem
        script: |
          sudo systemctl restart apache2
